version: '3.7'

services:
  web:
    build: .
    ports:
    - "5000:5000"
  mysql_db_container:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      TZ: America/Los_Angeles
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - "8080:8080"